name: Supabase Database Inactivity Prevention

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 on Monday
    - cron: '40 19 * * *'

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: GET REQUEST
        run: |
          curl --request GET \
            --url '${{ secrets.SUPABASE_URL }}/rest/v1/' \
            --header 'apikey: ${{ secrets.SUPABASE_SERVICE_KEY }}'
